#!/bin/bash
##
# Installation script for my dotfiles
# dotfiles -h; --help
#


# Exit script when a command fails.
set -o errexit # (a.k.a. set -e)

### Visual Helpers
RED=$(printf '\033[31m')
GREEN=$(printf '\033[32m')
YELLOW=$(printf '\033[33m')
BLUE=$(printf '\033[34m')
BOLD=$(printf '\033[1m')
RESET=$(printf '\033[m')
function header()   { echo -e "\n${BLUE}${BOLD}  $@ ${RESET}"; }
function success()  { echo -e "${GREEN} ✔ ${RESET} $@"; }
function error()    { echo -e "${RED} ✖ ${RESET} $@"; }
function arrow()    { echo -e "${YELLOW} ➜ ${RESET} $@"; }
sudo -v

while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
header Install
tempInstaller=mktemp
curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -o $tempInstaller
sh $tempInstaller --unattended
success "git install done"
chsh -s $(which zsh)
zsh
